/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ns_shopping_mart;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;

/**
 *
 * @author Anjan
 */
public class Electronics extends javax.swing.JFrame {

    /**
     * Creates new form Electronics
     */
    public Electronics() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton_item01 = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton_item02 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton_item03 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jRadioButton_item04 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jTextField_id = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel10.setForeground(new java.awt.Color(255, 51, 51));
        jLabel10.setText("item 01");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(150, 60, 48, 16);

        jLabel3.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("10% off");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 30, 50, 19);

        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Price : 50,000");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(120, 10, 80, 16);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\NS_Shopping_Mart\\Image\\HP felio 13.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 210, 150);

        jRadioButton_item01.setBackground(new java.awt.Color(153, 255, 153));
        jRadioButton_item01.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton_item01.setText("Add to cart");
        jRadioButton_item01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_item01ActionPerformed(evt);
            }
        });

        jPanel2.setLayout(null);

        jLabel11.setForeground(new java.awt.Color(153, 255, 51));
        jLabel11.setText("item 02");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 120, 60, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("Price : 40,000");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(80, 120, 90, 20);

        jLabel5.setIcon(new javax.swing.ImageIcon("E:\\NS_Shopping_Mart\\Image\\Lenevo Ideapad 300.jpg")); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(0, 0, 190, 150);

        jRadioButton_item02.setBackground(new java.awt.Color(153, 255, 153));
        jRadioButton_item02.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton_item02.setText("Add to cart");
        jRadioButton_item02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_item02ActionPerformed(evt);
            }
        });

        jPanel3.setLayout(null);

        jLabel12.setForeground(new java.awt.Color(255, 102, 102));
        jLabel12.setText("item 03");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(10, 30, 42, 16);

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Price : 30000 ");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(0, 10, 90, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon("E:\\NS_Shopping_Mart\\Image\\axon_10_pro.jpg")); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(0, 0, 210, 170);

        jRadioButton_item03.setBackground(new java.awt.Color(153, 255, 153));
        jRadioButton_item03.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton_item03.setText("Add to cart");
        jRadioButton_item03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_item03ActionPerformed(evt);
            }
        });

        jPanel4.setLayout(null);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("item 04");
        jPanel4.add(jLabel13);
        jLabel13.setBounds(70, 130, 60, 16);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Price : 15000");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(30, 100, 80, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon("E:\\NS_Shopping_Mart\\Image\\cropped-Y9-Prime-KV-Both-Colour-Options-1152x2052.png")); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(0, 0, 180, 170);

        jRadioButton_item04.setBackground(new java.awt.Color(153, 255, 153));
        jRadioButton_item04.setForeground(new java.awt.Color(0, 0, 0));
        jRadioButton_item04.setText("Add to cart");
        jRadioButton_item04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_item04ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setText("Cancel");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(153, 255, 153));
        jButton2.setText("Bye now");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Enter id :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton_item01, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(jRadioButton_item03, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRadioButton_item04, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                    .addComponent(jRadioButton_item02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel14)
                .addGap(40, 40, 40)
                .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_item01)
                    .addComponent(jRadioButton_item02))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_item03)
                    .addComponent(jRadioButton_item04))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
long i=0, price=0,item01=50000,item02=40000,item03 = 30000,item04=15000;

    private void jRadioButton_item01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_item01ActionPerformed
        jRadioButton_item01.isSelected();
       
    }//GEN-LAST:event_jRadioButton_item01ActionPerformed

    private void jRadioButton_item02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_item02ActionPerformed
        jRadioButton_item02.isSelected();
        
    }//GEN-LAST:event_jRadioButton_item02ActionPerformed

    private void jRadioButton_item03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_item03ActionPerformed
       jRadioButton_item03.isSelected();
      
    }//GEN-LAST:event_jRadioButton_item03ActionPerformed

    private void jRadioButton_item04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_item04ActionPerformed
        jRadioButton_item04.isSelected();
       
    }//GEN-LAST:event_jRadioButton_item04ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
     
        if( jRadioButton_item01.isSelected())
        {
        price = price + item01;
        i++;
        }
        if( jRadioButton_item02.isSelected())
        {
        price = price + item02;
        i++;
        }
        if( jRadioButton_item03.isSelected())
        {
        price = price + item03;
        i++;
        }
        if( jRadioButton_item04.isSelected())
        {
        price = price + item04;
        i++;
        }
        try{
             String id = jTextField_id.getText();
             String N_price = Long.toString(price);
             String count = Long.toString(i);
             
                    
        FileWriter fw = new FileWriter("E:\\Electronics.txt",false);
        fw.write(id+"\n");
        fw.write(N_price+"\n");
        fw.write(count+"\n");
      

        
        fw.close();
        System.out.println("Saved");
        
        
    }
    catch(Exception e)
    {
    System.out.println(e);
    }
         
         Electronics_shoping mf = new Electronics_shoping();
         mf.setVisible(true);
         mf.pack();
         mf.setLocationRelativeTo(null);
         this.dispose();
         
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Home_page mf = new Home_page();
         mf.setVisible(true);
         mf.pack();
         mf.setLocationRelativeTo(null);
         this.dispose();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Electronics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Electronics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Electronics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Electronics.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Electronics().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButton_item01;
    private javax.swing.JRadioButton jRadioButton_item02;
    private javax.swing.JRadioButton jRadioButton_item03;
    private javax.swing.JRadioButton jRadioButton_item04;
    private javax.swing.JTextField jTextField_id;
    // End of variables declaration//GEN-END:variables
}
